### ISSUE TITLE
Implement React Router #20 (Story points: 0.5)

### ISSUE THREAD

**Issue by a-iacampo** [Eltom777/SOEN341-PicturePoint#34]
This will allow us to change pages #20

**Comment by Eltom777** [comment]
I'll help you for this task !

**Comment by a-iacampo** [comment]
Basic routing was added. However, there is a bug where refreshing the page returns the taskbar to the default position but doesn't update the route with it.

**Comment by a-iacampo** [comment]
React Router has been implemented with a few routes. Closing issue.
