### ISSUE TITLE
Followers/Following is generated from using firebase's Database (Story point: 1)

### ISSUE THREAD

**Issue by Eltom777** [Eltom777/SOEN341-PicturePoint#37]
Missing element to finish #24

**Comment by Eltom777** [comment]
I created this issue just in case you are not able to connect the profile page to firestorm. We'll be able to close #24 and merge it master, even if that part is missing.

**Comment by a-iacampo** [comment]
Successfully connected the user profile card information to firebase #31. Need to connect followers and following to the firebase database.

**Comment by a-iacampo** [comment]
Commit f91e796 includes the addition of get follower/followings function

**Comment by a-iacampo** [comment]
I don't understand how we are implementing the followers and followings. Needs clarification in the next meeting.

**Comment by Eltom777** [comment]
@digathomas has not yet completed the tasks #45. Will push to sprint 4

**Comment by a-iacampo** [comment]
Duplicate of #72
