### ISSUE TITLE
Modify the data structure for profile card and photos (Story Point: 0)

### ISSUE THREAD

**Issue by digathomas** [Eltom777/SOEN341-PicturePoint#58]
The user should hold an array of indexes of the profile cards and indexes of photos for efficiency.

**Comment by Eltom777** [comment]
Motivation for task: Currently, fetching data is done using a for loop. This slows down our application significantly. The database will have to be restructured.

**Comment by a-iacampo** [comment]
Currently updating database querying

**Comment by a-iacampo** [comment]
New firebase functions implemented efficiently. Closing issue
